[tool.poetry]
name = "yt-python-drops"
version = "0.1.0"
description = ""
authors = ["André Lima"]
readme = "README.md"
packages = [{include = "yt_python_drops"}]

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
